{{- define "libchart.ingress.tpl" -}}
apiVersion: extensions/v1beta1
kind: Ingress
{{ template "libchart.metadata" . }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{ include "libchart.annote" .Values.ingress.annotations | indent 4 }}
  {{- end }}
spec:
  rules:
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "libchart.fullname" $ }}
          servicePort: 80
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- define "libchart.ingress" -}}
{{- template "libchart.util.merge" (append . "libchart.ingress.tpl") -}}
{{- end -}}
