{{- define "libchart.secret.tpl" -}}
apiVersion: v1
kind: Secret
{{ template "libchart.metadata" . }}
type: Opaque
data: {}
{{- end -}}
{{- define "libchart.secret" -}}
{{- template "libchart.util.merge" (append . "libchart.secret.tpl") -}}
{{- end -}}
